apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-mysql
  template:
    metadata:
      labels:
        app: account-mysql
    spec:
      containers:
        - name: account-mysql
          image: docker.io/thamaraikannip/accountmysql:0.1
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: account-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: account-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: account-front
    spec:
      containers:
        - name: account-front
          image: docker.io/thamaraikannip/account:0.1
          ports:
            - containerPort: 9001
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          env:
            - name: DB_HOST
              value: "account-mysql"
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: account-front
spec:
  type: LoadBalancer
  ports:
    - port: 9001
  selector:
    app: account-front