version: '3.3'

networks:
  account:
    driver: bridge
    name: accountnetwork

services:

  ### MySQL Container
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    container_name: account-mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - account

  account:
    image: account
    build:
      context: ./
      dockerfile: Dockerfile-account
    container_name: account-app
    environment:
      SERVICE_PRECONDITION: "account-mysql:3306"
      DB_HOST: account-mysql
      DB_PORT: 3306
    ports:
      - 9001:9001
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - account
