apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-mysql
  template:
    metadata:
      labels:
        app: product-mysql
    spec:
      containers:
        - name: product-mysql
          image: docker.io/thamaraikannip/productmysql:0.1
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: product-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: product-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: product-front
    spec:
      containers:
        - name: product-front
          image: docker.io/thamaraikannip/product:0.1
          ports:
            - containerPort: 8687
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          env:
            - name: DB_HOST
              value: "product-mysql"
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: product-front
spec:
  type: LoadBalancer
  ports:
    - port: 8687
  selector:
    app: product-front