FROM maven:latest AS build
RUN mkdir -p /build
WORKDIR /build
COPY pom.xml /build
#Copy source code
COPY src /build/src
# Build application
RUN mvn clean install

FROM openjdk:17
MAINTAINER baeldung.com
COPY --from=build /build/target/*.jar  customer-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/customer-0.0.1-SNAPSHOT.jar"]