version: '3.3'

networks:
  customer:
    driver: bridge
    name: customernetwork

services:

  ### MySQL Container
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    container_name: customer-mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - customer

  customer:
    image: customer
    build:
      context: ./
      dockerfile: Dockerfile-customer
    container_name: customer-app
    environment:
      SERVICE_PRECONDITION: "customer-mysql:3306"
      DB_HOST: customer-mysql
      DB_PORT: 3306
    ports:
      - 9002:9002
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - customer
